const reports=[
{date:"2026-08-19",bias:"Cautious / Mildly Bearish",emoji:"🟡",summary:"Crude above $90, geopolitical uncertainty and weak global cues pressure sentiment, while FII/DII buying and strong Indian earnings provide a cushion.",metrics:[["Nifty","24,154.90"],["Crude",">$90"],["USD/INR","~₹95.68"],["FII + DII","Buying"]],news:[
["🛢️ Crude remains above $90","negative","high","Higher crude raises India's import bill and can pressure INR, inflation and fuel-sensitive sectors.","Aviation • Paints • Chemicals • Tyres • Logistics"],
["🌍 US/global cues remain weak","negative","high","Higher Treasury yields and weaker global risk appetite can weigh on Indian equities.","IT • Financials • Index sentiment"],
["💰 FII and DII buying","positive","high","Institutional buying can absorb some selling pressure.","Banks • Large caps • Broad market"],
["🇮🇳 Indian Q1 earnings remain strong","positive","high","Robust profit growth gives the market a fundamental cushion.","Banks • Autos • Metals • Pharma"],
["📉 Six-session Nifty decline","neutral","high","A prolonged decline increases short-covering potential, but support breaks can accelerate selling.","Nifty • Options"],
["💵 Rupee near ₹95.7/$","negative","medium","Currency weakness raises imported-cost pressure, while exporters may benefit.","IT positive • Importers negative"]],levels:[["24,300+","Recovery / bullish confirmation"],["24,250–24,300","First resistance"],["24,100","Key support"],["24,000","Major psychological support"]],radar:[["🟢 Bullish trigger","24,100 holds + reclaim 24,250–24,300"],["🔴 Bearish trigger","Break 24,100 with crude >$90"],["⚪ Avoid / chop","Choppy action between key levels"],["⚠️ Invalidation","Unexpected oil / geopolitical reversal"]]},
{date:"2026-08-18",bias:"Cautious / Bearish",emoji:"🔴",summary:"Crude above $91 and US-Iran uncertainty increased downside risk; 24,200 was the key support.",metrics:[["Nifty","24,287.65"],["Crude",">$91"],["Geopolitics","Risk ↑"],["FII/DII","Mixed"]],news:[["🛢️ Crude oil above $91","negative","high","Higher crude is a direct macro headwind for India.","Aviation • Paints • Chemicals • Tyres"],["⚠️ US-Iran ceasefire expired","negative","high","Geopolitical uncertainty supported oil and reduced risk appetite.","Broad market"],["📊 24,200 key support","neutral","high","A decisive break could open the 24,100–24,000 zone.","Nifty • Options"],["🏦 Domestic institutions buying","positive","medium","DII demand can cushion foreign selling.","Large caps • Banks"]],levels:[["24,400–24,450","Bullish recovery zone"],["24,300–24,350","Immediate battle"],["24,200","Major support"],["24,000","Next psychological level"]],radar:[["🟢 Bullish trigger","Hold 24,200 + reclaim 24,350"],["🔴 Bearish trigger","Break 24,200 decisively"],["⚪ Avoid / chop","First 15–30 minutes without confirmation"],["⚠️ Invalidation","Rapid crude / geopolitical relief"]]},
{date:"2026-08-17",bias:"Cautious",emoji:"🟡",summary:"Crude near $89 and US-Iran uncertainty were the main risks, while US equities, FPI buying and earnings offered support.",metrics:[["Nifty","24,354.85"],["Crude","~$89"],["FPI","Buying"],["Bias","Cautious"]],news:[["🛢️ Crude near $89","negative","high","Oil remained the dominant macro risk for India.","Aviation • Paints • Chemicals"],["🇺🇸 US equities supportive","positive","medium","Firm US equities helped prevent a deeper risk-off opening.","Large caps • Technology"],["💰 FPI buying improved","positive","high","Foreign buying offered a cushion after earlier selling pressure.","Broad market"],["📈 Indian earnings resilient","positive","medium","Strong revenue and profit growth supported medium-term fundamentals.","Banks • Autos • Metals • Pharma"]],levels:[["24,500+","Bullish control"],["24,400–24,500","Resistance"],["24,300","Key support"],["24,200","Breakdown level"]],radar:[["🟢 Bullish trigger","Reclaim 24,400"],["🔴 Bearish trigger","Break 24,300"],["⚪ Avoid / chop","24,300–24,400"],["⚠️ Invalidation","Oil / geopolitical shock"]]}
];
let current=reports[0];
const fmt=s=>new Date(s+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"});
function render(r){current=r;reportDate.textContent=fmt(r.date);headline.textContent=r.bias;score.textContent=r.emoji;summary.textContent=r.summary;metrics.innerHTML=r.metrics.map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");levels.innerHTML=r.levels.map(x=>`<div class="row"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");radar.innerHTML=r.radar.map(x=>`<div class="row"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("");renderNews();loadNote()}
function renderNews(){let q=search.value.toLowerCase(),f=filter.value;let a=current.news.filter(n=>(!q||n.join(" ").toLowerCase().includes(q))&&(f==="all"||n[1]===f||n[2]===f));count.textContent=a.length+" items";newsList.innerHTML=a.map(n=>`<article class="news"><div class="news-top"><div class="news-title">${n[0]}</div><span class="badge ${n[1]}">${n[1]==="positive"?"🟢":n[1]==="negative"?"🔴":"🟡"} ${n[2]==="high"?"HIGH":"WATCH"}</span></div><div class="why"><b>Why it matters</b><br>${n[3]}</div><div class="effect"><b>Likely market effect:</b> ${n[4]}</div></article>`).join("")}
function history(){document.getElementById("history").innerHTML=reports.map(r=>`<div class="history-row" data-date="${r.date}"><div><div class="history-date">${fmt(r.date)}</div><div class="preview">${r.summary.slice(0,105)}…</div></div><div class="bias">${r.emoji}<br>${r.bias}</div></div>`).join("");document.querySelectorAll(".history-row").forEach(x=>x.addEventListener("click",()=>{let r=reports.find(y=>y.date===x.dataset.date);if(r){render(r);scrollTo({top:0,behavior:"smooth"})}}))}
function key(){return"market-news-note-"+current.date}function loadNote(){note.value=localStorage.getItem(key())||""}
search.addEventListener("input",renderNews);filter.addEventListener("change",renderNews);todayBtn.addEventListener("click",()=>render(reports[0]));save.addEventListener("click",()=>{localStorage.setItem(key(),note.value);saved.textContent="Saved ✓";setTimeout(()=>saved.textContent="",1600)});
history();render(reports[0]);
